# Generated by Django 3.2.12 on 2022-04-23 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pastoratepagegalleryimage',
            old_name='elders_name',
            new_name='name_of_the_pastor',
        ),
    ]
