# Generated by Django 3.2.12 on 2022-04-22 03:54

from django.db import migrations
import wagtail.contrib.table_block.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='pray_with_us',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='tabled',
            field=wagtail.core.fields.StreamField([('table', wagtail.contrib.table_block.blocks.TableBlock())], blank=True),
        ),
    ]
