# Generated by Django 3.2.12 on 2022-04-23 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_embed_videos', '0007_auto_20211109_0511'),
        ('home', '0002_rename_elders_name_pastoratepagegalleryimage_name_of_the_pastor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worshippage',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtail_embed_videos.embedvideo'),
        ),
    ]
