# Generated by Django 3.2.12 on 2022-04-22 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailmedia', '0004_duration_optional_floatfield'),
        ('home', '0002_auto_20220422_0354'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='featured_media',
            field=models.ForeignKey(blank=True, help_text='Video or image to be displayed on the home page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailmedia.media'),
        ),
    ]
