# Generated by Django 3.2.12 on 2022-04-22 19:23

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailmedia', '0004_duration_optional_floatfield'),
        ('home', '0003_homepage_featured_media'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('media_text', models.CharField(blank=True, max_length=255)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailmedia.media')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='stream_media', to='home.homepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
