# Generated by Django 3.2.12 on 2022-04-24 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_worshippage_video'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomePageMedia',
        ),
    ]
