# Generated by Django 3.2.12 on 2022-03-27 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homepagegalleryimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='video_url',
            field=models.URLField(blank=True, verbose_name='Video URL'),
        ),
    ]
