# Generated by Django 3.2.12 on 2022-04-23 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_embed_videos', '0007_auto_20211109_0511'),
        ('home', '0004_homepagemedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtail_embed_videos.embedvideo'),
        ),
    ]
