# Generated by Django 3.2.12 on 2022-04-23 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_homepage_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='video_url',
        ),
    ]
