# Generated by Django 3.2.12 on 2022-03-30 07:10

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20220329_0639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prayerrequestpagegalleryimage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='prayerrequestpagegalleryimage',
            name='page',
        ),
        migrations.RemoveField(
            model_name='statementoffaithimage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='statementoffaithimage',
            name='page',
        ),
        migrations.AlterField(
            model_name='appointmentspageformfield',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_fields', to='home.appointmentspage'),
        ),
        migrations.AlterField(
            model_name='prayerrequestpageformfield',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_fields', to='home.prayerrequestpage'),
        ),
        migrations.DeleteModel(
            name='AppointmentsPageGalleryImage',
        ),
        migrations.DeleteModel(
            name='PrayerRequestPageGalleryImage',
        ),
        migrations.DeleteModel(
            name='StatementOffaithImage',
        ),
    ]
