# Generated by Django 3.2.12 on 2022-04-25 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_homegallerypage_homegallerypagegalleryimage_homegallerypagetag'),
    ]

    operations = [
        migrations.AddField(
            model_name='homegallerypagegalleryimage',
            name='photo_caption',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
