# Generated by Django 3.2.12 on 2022-03-27 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_inceptionpage_inceptionpagegalleryimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inceptionpage',
            old_name='body',
            new_name='church_history',
        ),
    ]
