# Generated by Django 3.2.12 on 2022-04-01 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20220330_0710'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactPageGalleryImage',
        ),
    ]
