# Generated by Django 3.2.12 on 2022-04-25 04:55

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_announcementpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcementpage',
            name='document_file',
        ),
        migrations.AddField(
            model_name='announcementpage',
            name='body',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
