# Generated by Django 3.2.12 on 2022-03-27 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('home', '0007_rename_body_inceptionpage_church_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='inceptionpagegalleryimage',
            name='side_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image'),
        ),
    ]
