# Generated by Django 3.2.12 on 2022-04-02 05:50

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_givepage_givepagegalleryimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='givepagegalleryimage',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_information', to='home.givepage'),
        ),
    ]
