# Generated by Django 3.2.12 on 2022-04-25 08:16

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20220425_0520'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcementpagegalleryimage',
            name='announcement_title',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
