# Generated by Django 3.2.12 on 2022-04-25 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_announcementpagegalleryimage_announcement_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcementpagegalleryimage',
            name='announcement_title',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
