# Generated by Django 3.2.12 on 2022-04-08 17:01

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_staffpage_staffpagegalleryimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inceptionpagegalleryimage',
            name='side_image',
        ),
        migrations.AlterField(
            model_name='inceptionpagegalleryimage',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='side_image', to='home.inceptionpage'),
        ),
    ]
