# Generated by Django 3.2.12 on 2022-04-08 17:29

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20220408_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='inceptionpage',
            name='more_history',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
