# Generated by Django 3.2.12 on 2022-04-08 17:38

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_inceptionpage_more_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='inceptionpage',
            name='church_philosophy',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='inceptionpage',
            name='membership',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
