# Generated by Django 3.2.12 on 2022-04-08 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20220408_1738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statementoffaithpage',
            name='intro',
        ),
    ]
