# Generated by Django 3.2.12 on 2022-05-18 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('home', '0015_auto_20220518_0531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='churchcarepage',
            name='video',
        ),
        migrations.RemoveField(
            model_name='missionspage',
            name='video',
        ),
        migrations.RemoveField(
            model_name='womenpage',
            name='video',
        ),
        migrations.RemoveField(
            model_name='youngadultspage',
            name='video',
        ),
        migrations.AddField(
            model_name='churchcarepage',
            name='hero_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='missionspage',
            name='hero_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='womenpage',
            name='hero_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='youngadultspage',
            name='hero_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
