# Generated by Django 3.2.12 on 2022-04-09 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_remove_statementoffaithpage_intro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='convenantpage',
            name='intro',
        ),
        migrations.DeleteModel(
            name='ConvenantPageImage',
        ),
    ]
