# Generated by Django 3.2.12 on 2022-05-30 12:36

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
        ('wagtailredirects', '0007_add_autocreate_fields'),
        ('wagtailimages', '0023_add_choose_permissions'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('home', '0017_churchcarepage_featured_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeaconsBoardPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.core.fields.RichTextField(blank=True)),
                ('side_story', wagtail.core.fields.RichTextField(blank=True)),
                ('more_story', wagtail.core.fields.RichTextField(blank=True)),
                ('profile_photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.RemoveField(
            model_name='staffpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='staffpagegalleryimage',
            name='page',
        ),
        migrations.RemoveField(
            model_name='staffpagegalleryimage',
            name='photograph',
        ),
        migrations.AddField(
            model_name='eldersboardpage',
            name='more_story',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='eldersboardpage',
            name='profile_photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='eldersboardpage',
            name='side_story',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.DeleteModel(
            name='EldersBoardPageGalleryImage',
        ),
        migrations.DeleteModel(
            name='StaffPage',
        ),
        migrations.DeleteModel(
            name='StaffPageGalleryImage',
        ),
    ]
