# Generated by Django 3.2.12 on 2022-04-12 08:34

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_childrenpage_childrenpagefaqs'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='weekly_activities',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
