# Generated by Django 3.2.12 on 2022-05-30 16:15

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('home', '0018_auto_20220530_1236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menpage',
            name='video',
        ),
        migrations.AddField(
            model_name='menpage',
            name='hero_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='menpage',
            name='men_blog_body',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='menpage',
            name='men_blog_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='menpage',
            name='about_body',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
    ]
