# Generated by Django 3.2.12 on 2022-05-30 16:39

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20220530_1615'),
    ]

    operations = [
        migrations.RenameField(
            model_name='womenpage',
            old_name='hero_image',
            new_name='featured_image',
        ),
        migrations.AddField(
            model_name='menpage',
            name='event_body',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='menpage',
            name='event_title',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='menpage',
            name='men_blog_title',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
