# Generated by Django 3.2.12 on 2022-05-30 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('home', '0020_auto_20220530_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='couplespage',
            name='video',
        ),
        migrations.AddField(
            model_name='couplespage',
            name='featured_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
