# Generated by Django 3.2.12 on 2022-04-12 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_adultspage_adultspagefaqs_discipleshippage_discipleshippagefaqs_worshippage_worshippagefaqs_youthpag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adultspage',
            old_name='convenant_body',
            new_name='about_body',
        ),
        migrations.RenameField(
            model_name='discipleshippage',
            old_name='convenant_body',
            new_name='about_body',
        ),
        migrations.RenameField(
            model_name='worshippage',
            old_name='convenant_body',
            new_name='about_body',
        ),
        migrations.RenameField(
            model_name='youthpage',
            old_name='convenant_body',
            new_name='about_body',
        ),
        migrations.AddField(
            model_name='adultspage',
            name='video',
            field=models.URLField(blank=True, verbose_name='Video URL'),
        ),
        migrations.AddField(
            model_name='discipleshippage',
            name='video',
            field=models.URLField(blank=True, verbose_name='Video URL'),
        ),
        migrations.AddField(
            model_name='worshippage',
            name='video',
            field=models.URLField(blank=True, verbose_name='Video URL'),
        ),
        migrations.AddField(
            model_name='youthpage',
            name='video',
            field=models.URLField(blank=True, verbose_name='Video URL'),
        ),
    ]
