# Generated by Django 3.2.12 on 2022-04-14 08:57

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('home', '0021_auto_20220412_0937'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageMinistry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('ministry_title', models.CharField(blank=True, max_length=250)),
                ('short_description', models.CharField(blank=True, max_length=2000)),
                ('icon_class', models.CharField(blank=True, max_length=250)),
                ('ministry_link', models.URLField(blank=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='ministries', to='home.homepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
