# Generated by Django 3.2.12 on 2022-04-14 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_homepageministry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepageministry',
            name='ministry_link',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
