# Generated by Django 3.2.12 on 2022-05-30 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='missionslisitingpage',
            name='page_intro',
        ),
        migrations.DeleteModel(
            name='missionsPageFaqs',
        ),
    ]
