# Generated by Django 3.2.12 on 2022-05-30 18:41

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0002_auto_20220530_1836'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissionsPageFaqs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('question', models.CharField(blank=True, max_length=800)),
                ('answer', models.CharField(blank=True, max_length=800)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='missions_ministry_faqs', to='missions.missionslisitingpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
