# Generated by Django 3.2.12 on 2022-06-01 08:30

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('missions', '0003_missionspagefaqs'),
    ]

    operations = [
        migrations.CreateModel(
            name='upcomingMissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('mission_title', models.CharField(blank=True, max_length=255, null=True)),
                ('mission_venue', models.CharField(blank=True, max_length=255, null=True)),
                ('mission_date', models.DateField(blank=True, null=True)),
                ('mission_body', wagtail.core.fields.RichTextField(blank=True)),
                ('mission_promo_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='missions_ministry_upcoming', to='missions.missionslisitingpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
