# Generated by Django 3.2.12 on 2022-06-02 03:02

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailmedia', '0004_duration_optional_floatfield'),
        ('wagtailcore', '0066_collection_management_permissions'),
        ('wagtail_embed_videos', '0007_auto_20211109_0511'),
        ('wagtailimages', '0023_add_choose_permissions'),
        ('missions', '0004_upcomingmissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='SummonsLisitingPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('page_title', models.CharField(blank=True, max_length=255, null=True)),
                ('hero_title', models.CharField(blank=True, max_length=255, null=True)),
                ('hero_caption', models.CharField(blank=True, max_length=255, null=True)),
                ('hero_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='upcomingSummons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('summons_title', models.CharField(blank=True, max_length=255, null=True)),
                ('summon_date', models.DateField(blank=True, help_text='Date of the summons', null=True)),
                ('Summon_video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtail_embed_videos.embedvideo')),
                ('audio_media', models.ForeignKey(blank=True, help_text='Video or image to be displayed on the home page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailmedia.media')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='summons_ministry_upcoming', to='missions.summonslisitingpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FeaturedSummons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField(blank=True, help_text='Date of the summons', null=True)),
                ('media', models.ForeignKey(blank=True, help_text='Video or image to be displayed on the home page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailmedia.media')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured_summons', to='missions.summonslisitingpage')),
                ('video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtail_embed_videos.embedvideo')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
